openapi: 3.0.0
info:
  version: 2017-08-29
  x-release: v4
  title: AWS Elemental MediaConvert Certificates Tags API
  description: AWS Elemental MediaConvert
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: mediaconvert
  x-aws-signingName: mediaconvert
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/mediaconvert-2017-08-29.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://mediaconvert.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaConvert multi-region endpoint
- url: https://mediaconvert.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaConvert multi-region endpoint
- url: http://mediaconvert.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaConvert endpoint for China (Beijing) and China (Ningxia)
- url: https://mediaconvert.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaConvert endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Tags
paths:
  /2017-08-29/tags/{arn}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListTagsForResource
      description: Retrieve the tags for a MediaConvert resource.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTagsForResourceResponse'
              examples:
                ListTagsForResource200Example:
                  summary: Default ListTagsForResource 200 response
                  x-microcks-default: true
                  value:
                    ResourceTags: example-value
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                ListTagsForResource480Example:
                  summary: Default ListTagsForResource 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                ListTagsForResource481Example:
                  summary: Default ListTagsForResource 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                ListTagsForResource482Example:
                  summary: Default ListTagsForResource 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                ListTagsForResource483Example:
                  summary: Default ListTagsForResource 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                ListTagsForResource484Example:
                  summary: Default ListTagsForResource 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                ListTagsForResource485Example:
                  summary: Default ListTagsForResource 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: arn
        in: path
        required: true
        description: The Amazon Resource Name (ARN) of the resource that you want to list tags for. To get the ARN, send a GET request with the resource name.
        schema:
          type: string
      summary: Amazon MediaConvert List Tags for Resource
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Tags
    put:
      operationId: UntagResource
      description: Remove tags from a MediaConvert queue, preset, or job template. For information about tagging, see the User Guide at https://docs.aws.amazon.com/mediaconvert/latest/ug/tagging-resources.html
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UntagResourceResponse'
              examples:
                UntagResource200Example:
                  summary: Default UntagResource 200 response
                  x-microcks-default: true
                  value: {}
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                UntagResource480Example:
                  summary: Default UntagResource 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                UntagResource481Example:
                  summary: Default UntagResource 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                UntagResource482Example:
                  summary: Default UntagResource 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                UntagResource483Example:
                  summary: Default UntagResource 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                UntagResource484Example:
                  summary: Default UntagResource 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                UntagResource485Example:
                  summary: Default UntagResource 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: arn
        in: path
        required: true
        description: The Amazon Resource Name (ARN) of the resource that you want to remove tags from. To get the ARN, send a GET request with the resource name.
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tagKeys:
                  description: The keys of the tags that you want to remove from the resource.
                  type: array
                  items:
                    $ref: '#/components/schemas/__string'
      summary: Amazon MediaConvert Untag Resource
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Tags
  /2017-08-29/tags:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: TagResource
      description: Add tags to a MediaConvert queue, preset, or job template. For information about tagging, see the User Guide at https://docs.aws.amazon.com/mediaconvert/latest/ug/tagging-resources.html
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResourceResponse'
              examples:
                TagResource200Example:
                  summary: Default TagResource 200 response
                  x-microcks-default: true
                  value: {}
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                TagResource480Example:
                  summary: Default TagResource 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                TagResource481Example:
                  summary: Default TagResource 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                TagResource482Example:
                  summary: Default TagResource 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                TagResource483Example:
                  summary: Default TagResource 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                TagResource484Example:
                  summary: Default TagResource 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                TagResource485Example:
                  summary: Default TagResource 485 response
                  x-microcks-default: true
                  value: {}
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - arn
              - tags
              properties:
                arn:
                  description: The Amazon Resource Name (ARN) of the resource that you want to tag. To get the ARN, send a GET request with the resource name.
                  type: string
                tags:
                  description: The tags that you want to add to the resource. You can tag resources with a key-value pair or with only a key.
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/__string'
      summary: Amazon MediaConvert Tag Resource
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Tags
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    BadRequestException: {}
    NotFoundException: {}
    ResourceTags:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: The Amazon Resource Name (ARN) of the resource.
        Tags:
          allOf:
          - $ref: '#/components/schemas/__mapOf__string'
          - xml:
              name: tags
            description: The tags for the resource.
      description: The Amazon Resource Name (ARN) and tags for an AWS Elemental MediaConvert resource.
    TagResourceResponse:
      type: object
      properties: {}
    ForbiddenException: {}
    ConflictException: {}
    UntagResourceResponse:
      type: object
      properties: {}
    __string:
      type: string
    InternalServerErrorException: {}
    TooManyRequestsException: {}
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    ListTagsForResourceResponse:
      type: object
      properties:
        ResourceTags:
          allOf:
          - $ref: '#/components/schemas/ResourceTags'
          - xml:
              name: resourceTags
            description: The Amazon Resource Name (ARN) and tags for an AWS Elemental MediaConvert resource.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/mediaconvert/
